require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/{rails,rake}"
    - "bin/bundle"
    - !ruby/regexp /old_and_unused\.rb$/
  NewCops: enable
  TargetRubyVersion: 3.2.2

Lint/AmbiguousBlockAssociation:
  Enabled: false
Metrics/AbcSize:
  CountRepeatedAttributes: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
