default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: <%= ENV["POSTGRES_DB"] %>
  pool: 3
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: materials_development

test:
  <<: *default
  database: materials_test

production:
  <<: *default
  database: <%= ENV["RDS_DB_NAME"] %>
  host: <%= ENV["RDS_HOSTNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  port: <%= ENV["RDS_PORT"] %>
  username: <%= ENV["RDS_USERNAME"] %>
